# Quaero Test Runner Configuration
# Supports two test modes: "mock" and "integration"

[test_runner]
# Directory where test files are located (do not include subdirs like api/ui)
# Test runner will automatically discover api/ and ui/ subdirectories
tests_dir = "./test"

# Directory where test results will be created
# Structure: {output_dir}/{test-name}-{datetime}/
output_dir = "./test/results"

# Build script location
build_script = "./scripts/build.ps1"  # Windows
# build_script = "./scripts/build.sh" # Linux/Mac

# Test mode: "mock" or "integration"
# - mock: Uses in-memory mock server, no real database, fast, isolated
#   Ideal for CI/CD pipelines, fast feedback, unit testing
# - integration: Uses real Quaero service, tests full stack, requires service running
#   Ideal for end-to-end testing, pre-release validation
test_mode = "mock"  # Default to mock for safety

[test_server]
# Test server binds to this port for serving test resources
port = 3333

[service]
# Service under test configuration
binary = "./bin/quaero.exe"              # Path to service executable
config = "./bin/quaero.toml"             # Path to service configuration
# port = 8085                            # Optional: Override port (pass --port flag to binary)
startup_timeout_seconds = 30             # How long to wait for service to start
